version: '3.9'
services:
  backend:
    container_name: server
    image: andriinadosha/nestjs
    working_dir: /app/packages/server
    command: yarn start:dev
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: ./packages/server
    ports:
      - "3001:3001"
    environment:
      MONGODB_URL: mongodb://mongo:27017/blindspot
    depends_on:
      - mongo

  frontend:
    container_name: client
    image: andriinadosha/nextjs
    working_dir: /app/packages/client
    command: npm run dev
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: ./packages/client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - 27017:27017

  nginx:
    image: nginx
    container_name: nginx_cache
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - cache_volume:/var/cache/nginx

volumes:
  mongodata: {}
  cache_volume: {}

