version: '3.9'
services:
  backend:
    container_name: backend
    image: andriinadosha/nestjs
    working_dir: /app/packages/server
    command: yarn start:dev
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: .
    ports:
      - 3001:3001
    environment:
      MONGODB_URL: mongodb://mongo:27017/blindspot
      # Very important thing inside the Docker there are no localhost, only names of service!
    depends_on:
      - mongo
      
  frontend:
    container_name: frontend
    image: andriinadosha/nextjs
    working_dir: /app/packages/client
    command: npm run dev
    volumes:
      - type: bind
      # [INFO] We utilise the "bind" volume because when we update the code, the container reflects our changes.
        source: .
        target: /app
    build:
      context: .
    ports:
      - 3000:3005   
    depends_on:
      - backend 

  mongo:
    image: mongo
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - 27017:27017
  
  telegraf:
    platform: linux/arm64
    container_name: telegraf
    image: telegraf:latest
    volumes:
      -  ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: "host"

  influxdb:
    platform: linux/arm64
    image: influxdb:latest
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb


  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    ports:
      - '3034:3034'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    network_mode: "host"

  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    network_mode: "host"

volumes:
  mongodata: {}
  grafana_data: {}
  influxdb_data: {}

